apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}

# NOTE: Le secret DB doit être créé manuellement dans Kubernetes
# Commande: kubectl create secret generic grafana-db-secret -n grafana --from-literal=db-password='VOTRE_MOT_DE_PASSE'